spring:
  graphql:
    graphiql:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-manager:8080/.well-known/jwks.json
  application:
    name: analytics-svc
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: org.fmazmz.analyticssvc
        spring.json.value.default.type: org.fmazmz.analyticssvc.model.MessageSentEvent
        spring.json.use.type.headers: false
      group-id: analytics-svc-group
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
server:
  port: ${SERVER_PORT:8084}