spring:
  application:
    name: analytics-svc

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: org.fmazmz.analyticssvc
        spring.json.value.default.type: org.fmazmz.analyticssvc.MessageSentEvent
        spring.json.use.type.headers: false
      group-id: analytics-svc-group