spring:
  application:
    name: auth-manager
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    issuer: auth-manager
    # HS256
    secret: ${JWT_SECRET}
    access-token-ttl: PT15M
    refresh-token-ttl: PT15M
  webauthn:
    rp-id: localhost
    rp-name: distributed-chat
    origins:
      - http://localhost:3000
      - http://localhost:8080
    ceremony-ttl: PT5M
